cno = int(input("Enter consumer number: "))
cname = input("Enter consumer name: ")
pr = int(input("Enter present month reading: "))
lr = int(input("Enter last month redaing: "))
cost = float(input("Enter cost per unit: "))
bill = cost*(pr-lr)
print("Consumer number: ", cno)
print("Consumer name: ", cname)
print("Current Bill: ",bill)